<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<title>Test answers</title>

<style>
<!--
 /* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	text-indent:1.0cm;
	font-size:12.0pt;
	font-family:"Times New Roman";}
h1
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:3.0pt;
	margin-left:0cm;
	text-align:center;
	text-indent:1.0cm;
	page-break-after:avoid;
	font-size:22.0pt;
	font-family:"Times New Roman";}
p.MsoHeader, li.MsoHeader, div.MsoHeader
	{margin:0cm;
	margin-bottom:.0001pt;
	text-indent:1.0cm;
	font-size:12.0pt;
	font-family:"Times New Roman";}
p.MsoFooter, li.MsoFooter, div.MsoFooter
	{margin:0cm;
	margin-bottom:.0001pt;
	text-indent:1.0cm;
	font-size:12.0pt;
	font-family:"Times New Roman";}
p.Question, li.Question, div.Question
	{margin-top:12.0pt;
	margin-right:0cm;
	margin-bottom:3.0pt;
	margin-left:0cm;
	text-align:justify;
	font-size:12.0pt;
	font-family:"Times New Roman";
	font-weight:bold;}
p.Answer, li.Answer, div.Answer
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:2.0pt;
	margin-left:0cm;
	text-align:justify;
	text-indent:1.0cm;
	font-size:12.0pt;
	font-family:"Times New Roman";}
@page Section1
	{size:595.3pt 841.9pt;
	margin:42.55pt 1.0cm 2.0cm 1.0cm;}
div.Section1
	{page:Section1;}
-->
</style>

</head>

<body lang=BG>

<div class=Section1>

<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
 style='margin-left:.25pt;border-collapse:collapse;border:none'>
